import { siteConfig } from "@/lib/site-config";

interface PrintReportOptions {
  title: string;
  subtitle?: string;
  contentHtml: string;
}

/**
 * Opens a new tab with a branded, print-ready rendering of an agent
 * response and triggers the browser's print dialog — the user's "Save as
 * PDF" destination there is how this becomes a PDF report. There is no
 * server-side PDF generation involved.
 *
 * `contentHtml` is expected to be the already-rendered `.innerHTML` of a
 * <MarkdownRenderer> instance (captured from the live DOM), not raw
 * user/model text — this is what makes writing it straight into
 * `document.write` safe here. <MarkdownRenderer> uses react-markdown
 * WITHOUT the rehype-raw plugin, so literal HTML/script-like text inside an
 * agent's markdown is escaped and rendered as plain text, never as live DOM
 * nodes; the only real elements in that subtree are the ones our own
 * component overrides produced. If rehype-raw (or any other raw-HTML
 * passthrough) is ever added to MarkdownRenderer, this function must be
 * revisited — it would no longer be safe to trust `contentHtml` this way.
 */
export function openPrintReport({ title, subtitle, contentHtml }: PrintReportOptions): boolean {
  const win = window.open("", "_blank", "noopener,noreferrer,width=900,height=1100");
  if (!win) return false;

  const generatedAt = new Date().toLocaleString(undefined, { dateStyle: "long", timeStyle: "short" });

  win.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)} — ${escapeHtml(siteConfig.shortName)} Technical Summary</title>
<style>
  @page { margin: 2.2cm 1.8cm; }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, "Segoe UI", Inter, Arial, sans-serif;
    color: #1a1a1f;
    background: #ffffff;
    margin: 0;
    padding: 0 0 3rem;
    line-height: 1.55;
  }
  .masthead {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1.6rem 2rem;
    border-bottom: 3px solid #6366f1;
    margin-bottom: 1.75rem;
  }
  .wordmark {
    font-size: 1.35rem;
    font-weight: 800;
    letter-spacing: -0.01em;
    background: linear-gradient(90deg, #6366f1, #a855f7);
    -webkit-background-clip: text;
    background-clip: text;
    color: transparent;
  }
  .masthead-meta { text-align: right; font-size: 0.75rem; color: #6b7280; }
  .report-title { font-size: 1.3rem; font-weight: 700; margin: 0 2rem 0.25rem; }
  .report-subtitle { font-size: 0.85rem; color: #6b7280; margin: 0 2rem 1.5rem; }
  .report-body { padding: 0 2rem; font-size: 0.92rem; }
  .report-body pre, .report-body code { font-family: "SFMono-Regular", Consolas, monospace; }
  .report-body table { border-collapse: collapse; width: 100%; margin: 0.75rem 0; }
  .report-body th, .report-body td { border: 1px solid #e5e7eb; padding: 0.4rem 0.6rem; text-align: left; font-size: 0.85rem; }
  .report-body thead { background: #f4f4f6; }
  .report-body a { color: #4f46e5; }
  .footer {
    margin: 2.5rem 2rem 0;
    padding-top: 1rem;
    border-top: 1px solid #e5e7eb;
    font-size: 0.7rem;
    color: #9ca3af;
  }
</style>
</head>
<body>
  <div class="masthead">
    <span class="wordmark">${escapeHtml(siteConfig.shortName)}</span>
    <span class="masthead-meta">Technical Summary<br />Generated ${escapeHtml(generatedAt)}</span>
  </div>
  <h1 class="report-title">${escapeHtml(title)}</h1>
  ${subtitle ? `<p class="report-subtitle">${escapeHtml(subtitle)}</p>` : ""}
  <div class="report-body">${contentHtml}</div>
  <div class="footer">${escapeHtml(siteConfig.legalEntityName)} · Generated by ${escapeHtml(
    siteConfig.shortName
  )} AI Agents · Review before acting on any recommendation where professional judgment is warranted.</div>
</body>
</html>`);
  win.document.close();
  win.focus();
  // Give the new document a tick to paint before invoking print — the
  // styles above are all inline/embedded, but some browsers still need a
  // frame after document.write() before print() reflects the final layout.
  setTimeout(() => win.print(), 300);
  return true;
}

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
