import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalSection, LegalList } from "@/components/legal/legal-page";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = {
  title: `Terms of Service — ${siteConfig.name}`,
  description: `Terms governing use of ${siteConfig.name} by individuals, minors with guardian consent, and business entities.`,
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="August 5, 2026">
      <LegalSection heading="1. Agreement to these Terms">
        <p>
          These Terms of Service (&quot;Terms&quot;) form a binding agreement between you and{" "}
          {siteConfig.legalEntityName}, registered at {siteConfig.legalEntityAddress} (&quot;
          {siteConfig.shortName}&quot;, &quot;we&quot;, &quot;us&quot;), governing your access to
          and use of the {siteConfig.name} website, AI Agents, and SaaS Microservices
          (together, the &quot;Service&quot;). By creating an account, accessing, or paying for
          the Service, you agree to these Terms. If you do not agree, do not use the Service.
        </p>
      </LegalSection>

      <LegalSection heading="2. Who can use the Service">
        <p>
          The Service is offered to three categories of users, each subject to the additional
          conditions below:
        </p>
        <LegalList
          items={[
            <>
              <strong>Individual adults</strong> — anyone who has reached the age of majority in
              their jurisdiction (generally {siteConfig.ageOfMajorityDefault}) and has the legal
              capacity to enter into a binding contract.
            </>,
            <>
              <strong>Minors</strong> — individuals under the age of majority but at least{" "}
              {siteConfig.minimumAgeWithoutConsent} years old may use the Service only with the
              verifiable consent and direct involvement of a parent or legal guardian. The
              consenting parent or guardian must (a) accept these Terms on the minor&apos;s
              behalf, (b) be the named account holder and paying party for any subscription or
              purchase, and (c) supervise the minor&apos;s use of AI Agents. We do not
              knowingly permit account creation, unsupervised checkout, or direct payment by
              anyone under {siteConfig.minimumAgeWithoutConsent}. See our{" "}
              <Link href="/privacy">Privacy Policy</Link> for how we handle minors&apos; data.
            </>,
            <>
              <strong>Legal entities and businesses</strong> — a company, partnership, or other
              organization may use the Service through an authorized representative who confirms
              they have the authority to bind that entity to these Terms. References to
              &quot;you&quot; in that context mean both the representative and the entity, jointly
              and severally where permitted by law.
            </>,
          ]}
        />
      </LegalSection>

      <LegalSection heading="3. AI Agents — scope and limitations">
        <p>
          {siteConfig.shortName} is automated software: the Service uses AI Agents and SaaS
          Microservices to generate informational content that helps you work through personal
          and business questions. It is not a professional service and does not involve review
          by a human professional. Please read the following limitations carefully:
        </p>
        <LegalList
          items={[
            "The Service provides general, automatically generated informational and educational content only. It is not professional advice, is not a substitute for advice from a qualified professional, and no AI Agent output should be treated as such.",
            "Outputs are generated by artificial intelligence and may be incomplete, outdated, or incorrect. You are responsible for independently verifying any output before relying on it for consequential decisions.",
            "We do not guarantee any particular outcome, business result, or accuracy level from use of an AI Agent or Microservice.",
            "You must not use the Service to make decisions in situations involving risk to health, safety, or life without appropriate independent professional guidance.",
            "For minors, AI Agent interactions must be supervised by the consenting parent or guardian and are not a substitute for parental guidance, teachers, or qualified counselors.",
          ]}
        />
      </LegalSection>

      <LegalSection heading="4. Accounts">
        <p>
          You are responsible for maintaining the confidentiality of your account credentials and
          for all activity under your account. Notify us immediately at{" "}
          <a href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</a> if you
          suspect unauthorized use.
        </p>
      </LegalSection>

      <LegalSection heading="5. Subscriptions, one-time purchases, and billing">
        <p>
          The Service is offered under paid subscription plans (billed monthly or annually) and
          one-time SaaS Microservice purchases. All payments are processed by our reseller of
          record, {siteConfig.paddleMerchantName} (&quot;Paddle&quot;), who is the merchant and
          seller of record for your order, handles applicable sales tax/VAT, and supports card
          payments, PayPal, Apple Pay, Google Pay, and IBAN/bank transfer. By making a purchase,
          you also agree to{" "}
          <a href="https://www.paddle.com/legal/checkout-buyer-terms" target="_blank" rel="noopener noreferrer">
            Paddle&apos;s Buyer Terms
          </a>
          . Refunds and cancellations are governed by our{" "}
          <Link href="/refund">Refund &amp; Cancellation Policy</Link>.
        </p>
      </LegalSection>

      <LegalSection heading="6. Acceptable use">
        <p>You agree not to use the Service to:</p>
        <LegalList
          items={[
            "Violate any applicable law or the rights of any third party.",
            "Attempt to extract, reverse engineer, or misuse the underlying AI models.",
            "Submit content that is unlawful, abusive, or that you do not have the right to share.",
            "Circumvent usage limits, security controls, or payment obligations.",
          ]}
        />
      </LegalSection>

      <LegalSection heading="7. Intellectual property">
        <p>
          We retain all rights in the Service, including the AI Agents, Microservices,
          software, and branding. You retain ownership of content you submit, and grant us a
          license to process it solely to provide and improve the Service, as described in our{" "}
          <Link href="/privacy">Privacy Policy</Link>.
        </p>
      </LegalSection>

      <LegalSection heading="8. Disclaimers and limitation of liability">
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available&quot; without
          warranties of any kind, to the maximum extent permitted by law. To the fullest extent
          permitted by applicable law, {siteConfig.shortName} will not be liable for indirect,
          incidental, or consequential damages arising from your use of the Service or reliance on
          AI-generated output. Nothing in these Terms limits liability that cannot be excluded
          under applicable law, including for consumers in jurisdictions that grant non-waivable
          statutory protections.
        </p>
      </LegalSection>

      <LegalSection heading="9. Termination">
        <p>
          You may stop using the Service and cancel your subscription at any time as described in
          our <Link href="/refund">Refund &amp; Cancellation Policy</Link>. We may suspend or
          terminate access for breach of these Terms, non-payment, or unlawful use.
        </p>
      </LegalSection>

      <LegalSection heading="10. Governing law">
        <p>
          These Terms are governed by the laws of {siteConfig.governingLawJurisdiction}, without
          regard to conflict-of-law principles, except where mandatory local consumer protection
          law provides otherwise for your jurisdiction.
        </p>
      </LegalSection>

      <LegalSection heading="11. Changes to these Terms">
        <p>
          We may update these Terms from time to time. Material changes will be notified via the
          Service or by email. Continued use after changes take effect constitutes acceptance.
        </p>
      </LegalSection>

      <LegalSection heading="12. Contact">
        <p>
          Questions about these Terms can be sent to{" "}
          <a href={`mailto:${siteConfig.legalEmail}`}>{siteConfig.legalEmail}</a> or{" "}
          <a href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</a>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
